package sampleproject;

public class ExceptionHandling {

	public static void main(String[] args) 
	{
		//Handle ArrayIndexOutOfBoundsException
	       try {
	            int[] array = new int[15];
	            System.out.println("Accessing array element at index 10: " + array[20]);
	        } 
	       catch (ArrayIndexOutOfBoundsException e) 
	       {
	            System.out.println("Exception caught: Array index out of bounds");
	            
	        }

	        // Handle Arithmetic Exception
	        try {
	            int a = 10;
	            int b = 0;
	            int result = a / b;
	            System.out.println("Result of division: " + result);
	        }
	        catch (ArithmeticException e) 
	        {
	            System.out.println("Exception caught: Arithmetic exception (division by zero)");
	            
	        }

	      System.out.println("program continues after exception handling");
}
	

	}
